#!/bin/sh -e

python=/opt/cleanpython26/bin/python

$python bootstrap.py \
        --find-links "$HOME/.buildout/download-cache/dist"

bin/buildout -c rpm.cfg \
             find-links="$HOME/.buildout/download-cache/dist"

$python -m compileall -q -f `pwd`/eggs || true
$python -m compileall -q -f `pwd`/src
